### ISSUE TITLE
Inspect "'k' is bigger than the number of the blocks" error

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3spatiotemporal#17]
``` r
library(mlr3spatiotemporal)

library(mlr3)
task <- tsk("ecuador")

# Instantiate Resampling
rcv <- rsmp("spcv-block")
rcv$param_set$values <- list(folds = 20)
rcv$instantiate(task)
#> Error in blockCV::spatialBlock(speciesData = points, theRange = self$param_set$values$range, : 'k' is bigger than the number of the blocks
```

<sup>Created on 2019-09-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by be-marc** [comment]
`range` or `cols` and `rows` are not set. Therefore, `ResamplingSpCVBlock` uses the default value of `cols` and  `rows`, which is `4`. You want to assign 20 folds to 16 blocks, which does not work.

**Comment by pat-s** [comment]
Thanks for the quick heads-up, saves me some time. Will account for it with an appropriate error msg. Maybe changing the default even.

**Comment by pat-s** [comment]
Now using `rows = 4` and `cols = 4` and returning a more informative error message if this combination is still < than `folds`.

5727d575974d1e94f4892ebb1b9fec2a342609dc
